# Generated by Django 3.0.2 on 2020-01-24 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hospital',
            name='is_active',
        ),
    ]
