# Generated by Django 3.0.2 on 2020-01-24 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0002_remove_hospital_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
