# Generated by Django 3.0.2 on 2020-01-28 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0003_hospital_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='attachment',
            field=models.ImageField(blank=True, null=True, upload_to='hospital/'),
        ),
    ]
