# Generated by Django 3.0.2 on 2020-01-28 05:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0004_hospital_attachment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hospital',
            name='attachment',
        ),
    ]
